name: s_webview_example
description: Example app demonstrating the usage of s_webview package
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_webview: 
    path: ../

  webviewx2: ^2.1.0
  s_dropdown: ^2.1.0
  s_toggle: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

dependency_overrides:

flutter:
  uses-material-design: true
