name: s_webview
description: A Flutter package that provides an enhanced WebView widget with smooth animations and loading states
version: 1.0.3
homepage: https://github.com/SoundSliced/s_webview
repository: https://github.com/SoundSliced/s_webview
issue_tracker: https://github.com/SoundSliced/s_webview/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  atomic_webview: ^0.0.7
  flutter_animate: ^4.5.2
  ticker_free_circular_progress_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
