name: s_webview
description: A Flutter package for myWebView functionality
version: 0.0.1
homepage: https://github.com/SoundSliced/ss_webview
repository: https://github.com/SoundSliced/ss_webview
issue_tracker: https://github.com/SoundSliced/ss_webview/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  atomic_webview: ^0.0.7
  flutter_animate: ^4.5.2
  ticker_free_circular_progress_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
